# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NWQxNTIxOTFlOTUzNDkxZjVkMGRkMjdjMDExY2Q3ZjRkMDcxMTMyNWU1NzU5N2I1NzNjZDAyYTZiOTkyYTYxNjVhYmVkOGZiMDhlMDNhZTZiYTg4YzkyNGJhZGUxYmM2NTA5OWViZTUyOTRlZDEwY2UxN2I2MTJhM2NjYWExZmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
