# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjBiNjllY2MwZDI1ZmZjZTZjYTU3NmExN2FhNjAwZGYwNGZmMjc0OGRlZDk3NzYwZmI0ZDkxOTEyZDFlN2I2ZmZkZDZhODAxYzgyNzQxYWI5Mzk3ZjgzNjEyMDQ4NGYyOWRkMjAxMmVmNWU4YmFmZjU5NDI3NGIzM2FmNTdjODc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
